[project]
name = "dataist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.6.8",
    "graphviz>=0.21",
    "ipython>=9.4.0",
    "langchain>=0.3.27",
    "langchain-core>=0.3.72",
    "langchain-experimental>=0.3.4",
    "langchain-openai>=0.3.28",
    "langgraph>=0.6.2",
    "pandas>=2.3.1",
    "python-dotenv>=1.1.1",
]
